### ISSUE TITLE
How to communicate with current weather module ?

### ISSUE THREAD

**Issue by emrahaslan** [hangorazvan/compliments_plus#2]
Hi, I love that module but I thought that is beyond on default compliment module.

I want to use that module to alert weather warns to clients working with current default weather module

Also I have .svg icon set for each situation. The only thing I want to show image and text depending on current weather.

For ınstance if it is rainy , the module will show image + rainy text 

How can achieve this ?

I see  these code , but unable to undesrtand who is sending notification.

`notificationReceived: function(notification, payload, sender) {
		if (notification === "Weather data") {
			this.setCurrentWeatherType(payload.data);
		}
	},`

**Comment by hangorazvan** [comment]
The module is already communicate with weather or currentweather and display the weather condition:
[			day_sunny : [
				"Sunny"
			],
			day_cloudy : [
				"Cloudy",
			],
			cloudy : [
				"Cloudy"
			],
			cloudy_windy : [
				"Cloudy windy"
			],
			showers : [
				"Rain shower"
			],
			rain : [
				"Raining"
			],
			thunderstorm : [
				"Thunderstorm"
			],
			snow : [
				"Snowing"
			],
			fog : [
				"It's Fog"
			],
			night_clear : [
				"Clear night"
			],
			night_cloudy : [
				"Night cludy"
			],
			night_showers : [
				"Night showers"
			],
			night_rain : [
				"Raining night"
			],
			night_thunderstorm : [
				"Thunderstorm night"
			],
			night_snow : [
				"Snowing night"
			],
			night_alt_cloudy_windy : [
				"Night clouds and wind"
			], ](url)

Regarding svg icon is not implemented yet to display symbols or any weather icons.

**Comment by hangorazvan** [comment]
@emrah_asl for icons on currentweather compliments (I don know if it works for new weather module) you can replace in compliments.js
```
	compliment.lastElementChild.remove();
	wrapper.appendChild(compliment);
```
with
```
	compliment.lastElementChild.remove();
	compliment.innerHTML = complimentText;
	wrapper.appendChild(compliment);
```
then in config put
```
	day_sunny : [
		"<i class='wi wi-day-sunny'></i> Sunny day!"
	],
```
the weather icons are already loaded in currentweather.js but you can put in compliments.js
```
	getStyles: function () {
		return ["weather-icons.css"];
	},
```
